logo: "images/me_croped.jpg?raw=true"
description: >
  <br><b>Meher Boulaabi</b><br>
  <br>PhD Researcher in AI & Medical Imaging<br>  
  <br>ğŸ“ Location: Lens, France<br>
  <br>ğŸ“ Phone: +33 7 82 92 00 74<br>
  <br>ğŸ“§ Email: boulaabimeher.54@gmail.com<br>
  <br>
  <hr>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
