title: MEHER BOULAABI
logo: "images/me_croped.jpg?raw=true"
description: >
  <br> PhD Researcher in AI & Medical Imaging <br>
  <br> Location: Lens, France <br>
  <br> Phone: +33 782 92 00 74 <br>
  <br> Email: boulaabimeher.54@gmail.com <br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
